/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossarioIndexRouteImport } from './routes/glossario.index'
import { Route as TrabalhoPisPasep2026AbonoSalarialRouteImport } from './routes/trabalho.pis-pasep-2026-abono-salarial'
import { Route as PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRouteImport } from './routes/previdencia.aposentadoria-inss-2026-regras-tabela-prova-de-vida'
import { Route as ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRouteImport } from './routes/impostos.imposto-de-renda-2026-tabela-prazos-restituicao'
import { Route as GlossarioOQueEChar123termChar125RouteImport } from './routes/glossario.o-que-e-{$term}'
import { Route as BeneficiosCalendarioBolsaFamilia2026RouteImport } from './routes/beneficios.calendario-bolsa-familia-2026'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioIndexRoute = GlossarioIndexRouteImport.update({
  id: '/glossario/',
  path: '/glossario/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhoPisPasep2026AbonoSalarialRoute =
  TrabalhoPisPasep2026AbonoSalarialRouteImport.update({
    id: '/trabalho/pis-pasep-2026-abono-salarial',
    path: '/trabalho/pis-pasep-2026-abono-salarial',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute =
  PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRouteImport.update({
    id: '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida',
    path: '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute =
  ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRouteImport.update({
    id: '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao',
    path: '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao',
    getParentRoute: () => rootRouteImport,
  } as any)
const GlossarioOQueEChar123termChar125Route =
  GlossarioOQueEChar123termChar125RouteImport.update({
    id: '/glossario/o-que-e-{$term}',
    path: '/glossario/o-que-e-{$term}',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeneficiosCalendarioBolsaFamilia2026Route =
  BeneficiosCalendarioBolsaFamilia2026RouteImport.update({
    id: '/beneficios/calendario-bolsa-familia-2026',
    path: '/beneficios/calendario-bolsa-familia-2026',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/beneficios/calendario-bolsa-familia-2026': typeof BeneficiosCalendarioBolsaFamilia2026Route
  '/glossario/o-que-e-{$term}': typeof GlossarioOQueEChar123termChar125Route
  '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao': typeof ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute
  '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida': typeof PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute
  '/trabalho/pis-pasep-2026-abono-salarial': typeof TrabalhoPisPasep2026AbonoSalarialRoute
  '/glossario/': typeof GlossarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/beneficios/calendario-bolsa-familia-2026': typeof BeneficiosCalendarioBolsaFamilia2026Route
  '/glossario/o-que-e-{$term}': typeof GlossarioOQueEChar123termChar125Route
  '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao': typeof ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute
  '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida': typeof PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute
  '/trabalho/pis-pasep-2026-abono-salarial': typeof TrabalhoPisPasep2026AbonoSalarialRoute
  '/glossario': typeof GlossarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/beneficios/calendario-bolsa-familia-2026': typeof BeneficiosCalendarioBolsaFamilia2026Route
  '/glossario/o-que-e-{$term}': typeof GlossarioOQueEChar123termChar125Route
  '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao': typeof ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute
  '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida': typeof PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute
  '/trabalho/pis-pasep-2026-abono-salarial': typeof TrabalhoPisPasep2026AbonoSalarialRoute
  '/glossario/': typeof GlossarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/beneficios/calendario-bolsa-familia-2026'
    | '/glossario/o-que-e-{$term}'
    | '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao'
    | '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida'
    | '/trabalho/pis-pasep-2026-abono-salarial'
    | '/glossario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/beneficios/calendario-bolsa-familia-2026'
    | '/glossario/o-que-e-{$term}'
    | '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao'
    | '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida'
    | '/trabalho/pis-pasep-2026-abono-salarial'
    | '/glossario'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/beneficios/calendario-bolsa-familia-2026'
    | '/glossario/o-que-e-{$term}'
    | '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao'
    | '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida'
    | '/trabalho/pis-pasep-2026-abono-salarial'
    | '/glossario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BeneficiosCalendarioBolsaFamilia2026Route: typeof BeneficiosCalendarioBolsaFamilia2026Route
  GlossarioOQueEChar123termChar125Route: typeof GlossarioOQueEChar123termChar125Route
  ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute: typeof ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute
  PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute: typeof PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute
  TrabalhoPisPasep2026AbonoSalarialRoute: typeof TrabalhoPisPasep2026AbonoSalarialRoute
  GlossarioIndexRoute: typeof GlossarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario/': {
      id: '/glossario/'
      path: '/glossario'
      fullPath: '/glossario/'
      preLoaderRoute: typeof GlossarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalho/pis-pasep-2026-abono-salarial': {
      id: '/trabalho/pis-pasep-2026-abono-salarial'
      path: '/trabalho/pis-pasep-2026-abono-salarial'
      fullPath: '/trabalho/pis-pasep-2026-abono-salarial'
      preLoaderRoute: typeof TrabalhoPisPasep2026AbonoSalarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida': {
      id: '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida'
      path: '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida'
      fullPath: '/previdencia/aposentadoria-inss-2026-regras-tabela-prova-de-vida'
      preLoaderRoute: typeof PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao': {
      id: '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao'
      path: '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao'
      fullPath: '/impostos/imposto-de-renda-2026-tabela-prazos-restituicao'
      preLoaderRoute: typeof ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario/o-que-e-{$term}': {
      id: '/glossario/o-que-e-{$term}'
      path: '/glossario/o-que-e-{$term}'
      fullPath: '/glossario/o-que-e-{$term}'
      preLoaderRoute: typeof GlossarioOQueEChar123termChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios/calendario-bolsa-familia-2026': {
      id: '/beneficios/calendario-bolsa-familia-2026'
      path: '/beneficios/calendario-bolsa-familia-2026'
      fullPath: '/beneficios/calendario-bolsa-familia-2026'
      preLoaderRoute: typeof BeneficiosCalendarioBolsaFamilia2026RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BeneficiosCalendarioBolsaFamilia2026Route:
    BeneficiosCalendarioBolsaFamilia2026Route,
  GlossarioOQueEChar123termChar125Route: GlossarioOQueEChar123termChar125Route,
  ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute:
    ImpostosImpostoDeRenda2026TabelaPrazosRestituicaoRoute,
  PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute:
    PrevidenciaAposentadoriaInss2026RegrasTabelaProvaDeVidaRoute,
  TrabalhoPisPasep2026AbonoSalarialRoute:
    TrabalhoPisPasep2026AbonoSalarialRoute,
  GlossarioIndexRoute: GlossarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
