/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlossarioIndexRouteImport } from './routes/glossario.index'
import { Route as GlossarioOQueETermRouteImport } from './routes/glossario.o-que-e-$term'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioIndexRoute = GlossarioIndexRouteImport.update({
  id: '/glossario/',
  path: '/glossario/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioOQueETermRoute = GlossarioOQueETermRouteImport.update({
  id: '/glossario/o-que-e-$term',
  path: '/glossario/o-que-e-$term',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/glossario/o-que-e-$term': typeof GlossarioOQueETermRoute
  '/glossario/': typeof GlossarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/glossario/o-que-e-$term': typeof GlossarioOQueETermRoute
  '/glossario': typeof GlossarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/glossario/o-que-e-$term': typeof GlossarioOQueETermRoute
  '/glossario/': typeof GlossarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/glossario/o-que-e-$term' | '/glossario/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/glossario/o-que-e-$term' | '/glossario'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/glossario/o-que-e-$term'
    | '/glossario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GlossarioOQueETermRoute: typeof GlossarioOQueETermRoute
  GlossarioIndexRoute: typeof GlossarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario/': {
      id: '/glossario/'
      path: '/glossario'
      fullPath: '/glossario/'
      preLoaderRoute: typeof GlossarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario/o-que-e-$term': {
      id: '/glossario/o-que-e-$term'
      path: '/glossario/o-que-e-$term'
      fullPath: '/glossario/o-que-e-$term'
      preLoaderRoute: typeof GlossarioOQueETermRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GlossarioOQueETermRoute: GlossarioOQueETermRoute,
  GlossarioIndexRoute: GlossarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
